<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="draw2d" nsURI="http://www.eclipse.org/draw2d" nsPrefix="org.eclipse.draw2d">
  <eClassifiers xsi:type="ecore:EDataType" name="IFigure" instanceClassName="org.eclipse.draw2d.IFigure"
      serializable="false"/>
  <eSubpackages name="geometry" nsURI="http://www.eclipse.org/draw2d/geometry" nsPrefix="org.eclipse.draw2d.geometry">
    <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.draw2d.geometry.Point"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Dimension" instanceClassName="org.eclipse.draw2d.geometry.Dimension"/>
  </eSubpackages>
</ecore:EPackage>
