<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opm"
    nsURI="www.vainolo.com/phd/opm" nsPrefix="opm">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" eType="#//Rectangle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//NodeContainer"
        eOpposite="#//NodeContainer/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMObjectProcessDiagram" eSuperTypes="#//NodeContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true" eOpposite="#//Link/opd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMState" eSuperTypes="#//Node #//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMThing" eSuperTypes="#//Node #//NamedElement #//NodeContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMObject" eSuperTypes="#//OPMThing"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMProcess" eSuperTypes="#//OPMThing"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMStructuralLinkAggregator" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMAggregationLinkAggregator" eSuperTypes="#//OPMStructuralLinkAggregator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMExhibitionLinkAggregator" eSuperTypes="#//OPMStructuralLinkAggregator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMGeneralizationLinkAggregator" eSuperTypes="#//OPMStructuralLinkAggregator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incomingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opd" lowerBound="1" eType="#//OPMObjectProcessDiagram"
        eOpposite="#//OPMObjectProcessDiagram/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMProceduralLink" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bendpoints" upperBound="-1"
        eType="#//Point"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OPMAgentLink" eSuperTypes="#//OPMProceduralLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMInstrumentLink" eSuperTypes="#//OPMProceduralLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMConsumptionLink" eSuperTypes="#//OPMProceduralLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMResultLink" eSuperTypes="#//OPMProceduralLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMEffectLink" eSuperTypes="#//OPMProceduralLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="OPMStructuralLink" eSuperTypes="#//Link"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Rectangle" instanceClassName="org.eclipse.draw2d.geometry.Rectangle"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.draw2d.geometry.Point"/>
</ecore:EPackage>
